title: ChatBot
hero_image: images/banner.png
description: Learn how to program your own talking robot!
original_url: https://codeclubprojects.org/en-GB/scratch/chatbot?redirect=false
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: true
interests: "social"
technologies: "scratch"
steps:
  - title: Introduction
  - title: What you will need
  - title: 'Your ChatBot'
  - title: 'A talking ChatBot'
  - title: 'Making decisions'
  - title: 'Changing Location'
  - title: 'Challenge: Make your own ChatBot'
