title: ChatBot
hero_image: images/banner.png
description: Learn how to program your own talking robot!
original_url: https://codeclubprojects.org/en-GB/scratch/chatbot?redirect=false
theme: cc-prototype
duration: 2
listed: false
ingredient: false
copyedit: true
interests:
technologies:
steps:
  - title: Introduction
  - title: What you'll need
  - title: 'Step 1: Your ChatBot'
  - title: 'Step 2: A talking ChatBot'
  - title: 'Step 3: Making decisions'
  - title: 'Step 4: Changing Location'
  - title: 'Challenge: Make your own ChatBot'
