title: ChatBot
hero_image: images/banner.png
description: Learn how to program your own talking robot!
original_url: https://codeclubprojects.org/en-GB/scratch/chatbot?redirect=false
theme: cc-prototype
duration: 2
listed: false
ingredient: false
copyedit: false
interests:
technologies:
steps:
  - title: Introduction
  - title: What you'll need
  - title: 'Your ChatBot'
  - title: 'A talking ChatBot'
  - title: 'Making decisions'
  - title: 'Changing Location'
  - title: 'Challenge: Make your own ChatBot'
