title: ChatBot
hero_image: images/chatbot.png
subtitle:
description: Learn how to program your own talking robot!
original_url: https://codeclubprojects.org/en-GB/scratch/chatbot?redirect=false
theme: cc-prototype
published: true
steps:
  - title: Introduction
    duration: 10
