title: ChatBot
hero_image: images/banner.png
subtitle: Not sure one is needed.
description: Learn how to program your own talking robot!
original_url: https://codeclubprojects.org/en-GB/scratch/chatbot?redirect=false
theme: cc-prototype
published: false
steps:
  - title: Introduction
    duration: 10
  - title: What you'll need
    duration: 10
  - title: 'Step 1: Your ChatBot'
    duration: 10
  - title: 'Step 2: A talking ChatBot'
    duration: 10
  - title: 'Step 3: Making decisions'
    duration: 10
  - title: 'Step 4: Changing Location'
    duration: 10
  - title: 'Challenge: Make your own ChatBot'
    duration: 10
