title: ChatBot
hero_image: images/banner.png
subtitle: Not sure one is needed.
description: Learn how to program your own talking robot!
original_url: https://codeclubprojects.org/en-GB/scratch/chatbot
theme: cc-prototype
published: false
steps:
  - title: Introduction
    duration: 10
  - title: What you'll need
    duration: 10
  - title: Your ChatBot
    duration: 10
  - title: A talking ChatBot
    duration: 10
  - title: Making decisions
    duration: 10
  - title: Changing Location
    duration: 10
  - title: 'Challenge: Make your own ChatBot'
    duration: 10
